server:
  port: 9501

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000


zuul:
  prefix: /mldn-proxy
  ignored-services:
    "*"
  routes: 
    microcloud-provider-company: /company-proxy/** 
    microcloud-provider-dept: /dept-proxy/**
    microcloud-provider-upload: /upload-proxy/**



eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: gateway-9501.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

info:
  app.name: microcloud-zuul-gateway
  company.name: com.alen
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

spring:
  application:
    name: microcloud-zuul-gateway
