#端口
server:
  port: 8089
#eureka:
#  client: # 客户端进行Eureka注册的配置
#    service-url:
#      defaultZone: :http://localhost:8081/eureka/
#这在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: service-security
# 启用SpringSecurity的安全配置项
security:
      user:
            name: root # 认证用户名
            password: root # 认证密码
            role:
      basic:
       # 授权角色
        enabled: true


